- name: Authenticate and interact with Zscaler API
  hosts: localhost
  tasks:
    - name: Obtain authentication token from Zscaler API
      uri:
        url: "https://config.zpabeta.net/signin"
        method: POST
        body:
          client_id: "{{ lookup('env', 'ZSCALER_CLIENT_ID') }}"
          client_secret: "{{ lookup('env', 'ZSCALER_CLIENT_SECRET') }}"
          cloud_id: "{{ lookup('env', 'ZPA_CLOUD_ID') }}"
          customer_id: "{{ lookup('env', 'ZPA_CUSTOMER_ID') }}"
        body_format: json
        return_content: yes
      register: auth_response
