- name: Authenticate with Zscaler API
  hosts: localhost
  connection: local
  tasks:
    - name: Authenticate with Zscaler API
      uri:
        url: "{{ zscaler_cloud_url }}/api/v1/authenticatedSession"
        method: GET
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          username: "{{ zscaler_username }}"
          password: "{{ zscaler_password }}"
          apiKey: "{{ zscaler_api_key }}"
        return_content: yes
        validate_certs: no  # Only for testing
      register: auth_response

    - debug:
        var: auth_response
