---
- name: Connect to Zscaler Cloud
  hosts: d31kquknww6614.cloudfront.net
  tasks:
    - name: Authenticate with Zscaler API
      uri:
        url: "{{ zscaler_cloud_url }}/api/v1/authenticatedSession"
        method: GET
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          username: "{{ zscaler_username }}"
          password: "{{ zscaler_password }}"
          apiKey: "{{ zscaler_api_key }}"
        return_content: yes
      register: auth_response

    - name: Set Zscaler Auth Token
      set_fact:
        zscaler_auth_token: "{{ auth_response.json.token }}"

    - name: Get List of Users from Zscaler
      uri:
        url: "{{ zscaler_cloud_url }}/api/v1/users"
        method: GET
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ zscaler_auth_token }}"
        return_content: yes
      register: users_response
    
    - debug:
        var: users_response.json    
