- name: Authenticate with Zscaler API
  hosts: localhost
  connection: local
  tasks:
    - name: Authenticate with Zscaler API
      uri:
        url: https://config.zpabeta.net/api/v1/authenticatedSession"
        method: GET
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          client_id: "{{ zscaler_client_id }}"
          client_secret: "{{ zscaler_client_secret }}"
        return_content: yes
        validate_certs: no  # Only for testing
      register: auth_response

    - debug:
        var: auth_response
